-- AlterTable
ALTER TABLE "system_settings" ADD COLUMN     "academicYear" TEXT,
ADD COLUMN     "allowedBranches" TEXT,
ADD COLUMN     "allowedResumeFormats" TEXT DEFAULT 'pdf,docx',
ADD COLUMN     "autoApproveStudents" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "customCss" TEXT,
ADD COLUMN     "defaultMaxBacklogs" INTEGER DEFAULT 0,
ADD COLUMN     "defaultMinCgpa" DOUBLE PRECISION DEFAULT 6.0,
ADD COLUMN     "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableTwoFactor" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "loginBannerUrl" TEXT,
ADD COLUMN     "maxApplicationsPerStudent" INTEGER DEFAULT 10,
ADD COLUMN     "maxLoginAttempts" INTEGER DEFAULT 5,
ADD COLUMN     "maxResumeSize" INTEGER DEFAULT 2,
ADD COLUMN     "minPasswordLength" INTEGER DEFAULT 8,
ADD COLUMN     "notifyApplicationStatus" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyNewDrive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "notifyOnNewDrive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "placementEndDate" TIMESTAMP(3),
ADD COLUMN     "placementStartDate" TIMESTAMP(3),
ADD COLUMN     "primaryColor" TEXT DEFAULT '#3B82F6',
ADD COLUMN     "pushNotifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requireDriveApproval" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "requirePasswordComplexity" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "requiredProfileFields" TEXT,
ADD COLUMN     "secondaryColor" TEXT DEFAULT '#10B981',
ADD COLUMN     "sessionTimeout" INTEGER DEFAULT 3600,
ADD COLUMN     "smsNotifications" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "studentRegistrationOpen" BOOLEAN NOT NULL DEFAULT true;
